baseURL = "https://erlunsenioredu.us.to"
languageCode = "tw"
defaultContentLanguage = "tw"
title = "二崙樂齡學習中心"
theme = "KeepIt"

paginate = 50
enableEmoji = false
enableRobotsTXT = false
googleAnalytics = ""
contentDir = "content"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "帖文"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "類別"
    url = "/categories/"
    weight = 3
  
  [[menu.main]]
    name = "相簿"
    url = "/album/"
    weight = 4

  [[menu.main]]
    name = "關於"
    url = "/about"
    weight = 5

[params]
    since = 2019
    author = "二崙樂齡學習中心"               # Author's name
    subtitle = "二崙樂齡學習中心"       # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "other" # post or other
    dateFormatToUse = "" # set date format, default "2 January 2006"
    
    avatar = "/images/homepage/home.jpg" #comment it to use gravatar
    socialShare = true

    description = "" # site description
    keywords = "" # site keywords
    
[params.gravatar]
    #email = "a47744113@yahoo.com.tw"   #uncomment and insert your email address to use gravatar


[params.social]
Facebook = "profile.php?id=100069254726210"
[params.share]
Twitter = true
Facebook = true
#Reddit = true
#Linkedin = true
#Pinterest = true
#HackerNews = true
#Mix = true
#Tumblr = true
#VKontakte = true
#Douban = true
#Weibo = true

# Used only for Seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "Fastbyte01"

  [params.publisher]
    name = "Fastbyte01"

    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  [params.image]
    url = "cover.png"
    width = 800
    height = 600
